package com.example.ExpenseAndIncomeTracker.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

@Data
@DynamoDBTable(tableName = "Transactions")
public class Transaction {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String transactionId;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "DateIndex", attributeName = "userId")
    private String userId;

    @DynamoDBAttribute
    private BigDecimal amount;

    @DynamoDBAttribute
    private String type;

    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "DateIndex")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd hh:mm:ss")
    private Date createdAt;

    @DynamoDBAttribute
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd hh:mm:ss")
    private Date modifiedAt;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "CategoryIndex", attributeName = "category")
    private String category;

}
